/**
 * Generated by `deno task size --write`, which the showcase's own bundle task runs first - do not
 * edit by hand.
 *
 * The whole package bundled from its single entrypoint, minified, with nothing tree-shaken away.
 */
export const bundleSize: {raw: number, gzip: number, measuredAt: string} = {
    raw: 163678,
    gzip: 43497,
    measuredAt: "2026-09-19"
}
