/**
 * Measures what a consumer actually downloads for the whole of velodesign.
 *
 * `src/index.ts` is the package's only entrypoint, so bundling it minified is the honest ceiling:
 * every component, every stylesheet string, no tree-shaking a real app would get. The gzip figure
 * is the one that matters over the wire and is what the showcase leads with.
 *
 * Three ways to run it:
 *   deno task size            - print a human summary
 *   deno task size --json     - emit JSON, which the pull-request workflow diffs
 *   deno task size --write    - regenerate showcase/src/data/bundle-size.ts
 *
 * The showcase regenerates this on every `deno task bundle`, so the number on the home page is
 * measured from the source it was built with rather than from a value someone remembered to update.
 */

const root = new URL("../", import.meta.url).pathname
const entrypoint = `${root}src/index.ts`

/** Bundles the package the way a browser consumer would and returns the bytes on disk */
async function measure(): Promise<{raw: number, gzip: number}> {
    const outFile = await Deno.makeTempFile({suffix: ".js"})
    try {
        const bundle = new Deno.Command(Deno.execPath(), {
            args: ["bundle", "--minify", "--platform", "browser", "--quiet", "-o", outFile, entrypoint],
            cwd: root,
            stdout: "piped",
            stderr: "piped",
        })
        const result = await bundle.output()
        if (!result.success) {
            throw new Error(`deno bundle failed:\n${new TextDecoder().decode(result.stderr)}`)
        }
        const bytes = await Deno.readFile(outFile)
        return {raw: bytes.byteLength, gzip: await gzipSize(bytes)}
    } finally {
        await Deno.remove(outFile).catch(() => {})
    }
}

/**
 * Compressed size, which is what a consumer's browser actually pulls down.
 *
 * Worth knowing before comparing two of these: gzip output is **not** byte-identical across
 * machines - the same bundle measured 43497 here and 43496 on an ubuntu-24.04 runner, because the
 * zlib behind `CompressionStream` differs. `raw` is deterministic. So compare gzip only between
 * two measurements taken on the same machine, which is what the pull-request workflow does, and
 * never assert it against a committed value.
 */
async function gzipSize(bytes: Uint8Array): Promise<number> {
    const stream = new Blob([bytes as BlobPart]).stream().pipeThrough(new CompressionStream("gzip"))
    let total = 0
    for await (const chunk of stream) {
        total += (chunk as Uint8Array).byteLength
    }
    return total
}

/** Bytes as the showcase and the pull-request comment both spell them */
export function formatBytes(bytes: number): string {
    return `${(bytes / 1024).toFixed(1)} KB`
}

const generatedFile = `${root}showcase/src/data/bundle-size.ts`

async function writeGenerated(sizes: {raw: number, gzip: number}) {
    const contents = `/**
 * Generated by \`deno task size --write\`, which the showcase's own bundle task runs first - do not
 * edit by hand.
 *
 * The whole package bundled from its single entrypoint, minified, with nothing tree-shaken away.
 *
 * Deliberately carries no timestamp. A generated file that changes every day cannot be checked
 * against a fresh measurement in CI, because the check would start failing the next morning for
 * reasons that have nothing to do with the bundle.
 */
export const bundleSize: {raw: number, gzip: number} = {
    raw: ${sizes.raw},
    gzip: ${sizes.gzip}
}
`
    await Deno.writeTextFile(generatedFile, contents)
}

const sizes = await measure()
if (Deno.args.includes("--json")) {
    console.log(JSON.stringify(sizes))
} else {
    if (Deno.args.includes("--write")) {
        await writeGenerated(sizes)
    }
    console.log(`velodesign bundled from src/index.ts, minified`)
    console.log(`  raw   ${formatBytes(sizes.raw)} (${sizes.raw} bytes)`)
    console.log(`  gzip  ${formatBytes(sizes.gzip)} (${sizes.gzip} bytes)`)
}
